// SPDX-License-Identifier: AGPL-3.0-only
//! Anomaly event record for persistent security event logging.
//!
//! Anomaly events are generated by AnomalyDetector.evaluate() when a login
//! triggers a security rule (brute force, credential stuffing, etc.).
//! Persisted to anomaly_events table for admin dashboard queries.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Unique identifier for an anomaly event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AnomalyEventId(pub Uuid);

impl AnomalyEventId {
    pub fn new() -> Self {
        Self(Uuid::now_v7())
    }
}

impl Default for AnomalyEventId {
    fn default() -> Self {
        Self::new()
    }
}

/// Persistent anomaly event record.
///
/// Created when AnomalyDetector fires a rule during login.
/// Stored in anomaly_events table, queried via GetAnomalyEventLog RPC.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnomalyEventRecord {
    pub id: AnomalyEventId,
    /// Which anomaly rule triggered (e.g., "brute_force", "credential_stuffing").
    pub rule_id: String,
    /// Profile that triggered the rule (may be empty for IP-only rules).
    pub profile_id: String,
    /// Client IP address.
    pub ip_address: String,
    /// Human-readable description of what happened.
    pub description: String,
    /// Risk weight of the rule (from AnomalyRule.weight, 0-100).
    pub risk_score: i32,
    /// Reaction taken (allow, step_up, require_captcha, block, hard_no).
    pub reaction: String,
    pub timestamp: DateTime<Utc>,
}

impl AnomalyEventRecord {
    pub fn new(
        rule_id: impl Into<String>,
        profile_id: impl Into<String>,
        ip_address: impl Into<String>,
        description: impl Into<String>,
        risk_score: i32,
        reaction: impl Into<String>,
    ) -> Self {
        Self {
            id: AnomalyEventId::new(),
            rule_id: rule_id.into(),
            profile_id: profile_id.into(),
            ip_address: ip_address.into(),
            description: description.into(),
            risk_score,
            reaction: reaction.into(),
            timestamp: Utc::now(),
        }
    }
}
